### ISSUE TITLE
TypeError occurs when using dash notation to specify ports

### ISSUE THREAD

**Issue by lystena** [codingo/Interlace#102]
##### Description:
Latest build seems to have a bug with supporting dash notation.

##### Steps to reproduce:
1. pull latest and install
2. attempt to use a command with dash notation
```
echo 127.0.0.1 > targets.txt
interlace -tL ./targets.txt -p 80-81 -c 'nmap _target_ -p _port_'
```
##### Example
The output below shows a successful install; comma-delimited port command succeeding; followed by a dash notation command failing

```
[~]$ git clone https://github.com/codingo/Interlace
Cloning into 'Interlace'...
remote: Enumerating objects: 149, done.
remote: Counting objects: 100% (149/149), done.
remote: Compressing objects: 100% (107/107), done.
remote: Total 1200 (delta 68), reused 66 (delta 33), pack-reused 1051
Receiving objects: 100% (1200/1200), 248.28 KiB | 426.00 KiB/s, done.
Resolving deltas: 100% (657/657), done.
[~]$ cd Interlace 
[master][~/Interlace]$ sudo python3 setup.py install                
running install                                                     
running install_lib                      
...Snip...
Using /usr/local/lib/python3.7/site-packages/colorclass-2.2.0-py3.7.egg
Finished processing dependencies for Interlace==1.8.0
[master][~/Interlace]$ echo 127.0.0.1 > targets.txt 
*[master][~/Interlace]$ interlace -tL ./targets.txt -p 80 -c 'nmap _target_ -p _port_'
=====================================================
Interlace v1.8.0        by Michael Skelton (@codingo_)
                        & Sajeeb Lohani (@sml555_)
=====================================================
[19:53:52] [THREAD] [nmap 127.0.0.1 -p 80] Added to Queue 
Generated 1 commands in total
Repeat set to 1
Starting Nmap 7.70 ( https://nmap.org ) at 2020-04-17 19:53 AEST                                                                                                                                                                              
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00016s latency).

PORT   STATE  SERVICE
80/tcp closed http

Nmap done: 1 IP address (1 host up) scanned in 0.08 seconds

100%|██████████████████████████████████████████████████████████████
*[master][~/Interlace]$ interlace -tL ./targets.txt -p 80-81 -c 'nmap _target_ -p _port_'
=====================================================
Interlace v1.8.0        by Michael Skelton (@codingo_)
                        & Sajeeb Lohani (@sml555_)
=====================================================
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.8.0', 'console_scripts', 'interlace')()
  File "/usr/local/lib/python3.7/site-packages/Interlace-1.8.0-py3.7.egg/Interlace/interlace.py", line 32, in main
  File "/usr/local/lib/python3.7/site-packages/Interlace-1.8.0-py3.7.egg/Interlace/interlace.py", line 11, in build_queue
  File "/usr/local/lib/python3.7/site-packages/Interlace-1.8.0-py3.7.egg/Interlace/lib/core/input.py", line 289, in process_commands
  File "/usr/local/lib/python3.7/site-packages/Interlace-1.8.0-py3.7.egg/Interlace/lib/core/input.py", line 214, in _replace_variable_with_commands
  File "/usr/local/lib/python3.7/site-packages/Interlace-1.8.0-py3.7.egg/Interlace/lib/threader.py", line 27, in replace
TypeError: replace() argument 2 must be str, not int


```

**Comment by prodigysml** [comment]
Eek!  Good catch @lystena! I'll try looking into this soon and patch. Cheers!

**Comment by lystena** [comment]
No stress. Initially thought it was me; then I was hoping to find some time to just fix the bug and do a PR. instead here we are..

**Comment by lystena** [comment]
I suspect the problem is at the following:

https://github.com/codingo/Interlace/blob/master/Interlace/lib/core/input.py
line 214: 
```
new_task.replace(variable, replacement)
```
Setting the replacement type to a string seems to result in the problem being solved
```
new_task.replace(variable, str(replacement))
```
##### Output after change 
```
interlace -tL ./targets.txt -p 80 -c 'nmap _target_ -p _port_'
=====================================================
Interlace v1.8.0	by Michael Skelton (@codingo_)
                  	& Sajeeb Lohani (@sml555_)
=====================================================
[13:14:56] [92m[THREAD][39m [nmap 127.0.0.1 -p 80] Added to Queue 
[13:14:56] [92m[THREAD][39m [nmap 127.0.0.1 -p 81] Added to Queue 
Generated 2 commands in total
Repeat set to 1
Starting Nmap 7.70 ( https://nmap.org ) at 2020-04-18 13:14 AEST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00018s latency).

PORT   STATE  SERVICE
80/tcp closed http

Nmap done: 1 IP address (1 host up) scanned in 0.07 seconds

Starting Nmap 7.70 ( https://nmap.org ) at 2020-04-18 13:14 AEST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00016s latency).

PORT   STATE  SERVICE
81/tcp closed hosts2-ns

Nmap done: 1 IP address (1 host up) scanned in 0.07 seconds


```

**Comment by lystena** [comment]
@prodigysml looks like this is going stale. Not sure if it got updated in the end or if life got busy.

**Comment by prodigysml** [comment]
Hey @lystena,

Frankly I absolutely forgot about it! I'll try to fix it up soon! Sorry about that!

Cheers,
Sajeeb

**Comment by lystena** [comment]
no stress - I forgot about it too. Good stale bot - keep the humans accountable

**Comment by prodigysml** [comment]
Just put in a PR as a fix. Issue should be fixed as soon as approved.
