### ISSUE TITLE
Interlace cant be scripted

### ISSUE THREAD

**Issue by machinexa2** [codingo/Interlace#109]
Make more than one files .Eg: 3 files
```bash
file1
file2
file3
```
file1 contains data1, file2 contains data2 file3 contains data3. Here, data1 are just example, it could contain longer data like thousands.
Now script it using this command
```
ls | xargs | tr ' ' '\n' | while read filenames
do
cat $filenames
done
```
The output will be data1, data2 and data3. Now use interlace here:
```
ls | xargs | tr ' ' '\n' | while read filenames
do
interlace -tL $filenames -threads 10 -c "echo _target_"
done
```
It should print data1, data2 and data3 but it doesnt. It prints $filenames instead of data1,data2, data3
```
root@kali-linux:/tmp/interlace_testing# cat file1 file2 file3 
data1
data2
data3
data4
data5
data6
root@kali-linux:/tmp/interlace_testing# cat filelist 
file1
file2
file3
root@kali-linux:/tmp/interlace_testing# cat filelist  | while read filename
> do
> interlace -tL $filename -threads 8 -c "echo _target_"
> done
=====================================================
Interlace v1.8.2        by Michael Skelton (@codingo_)
                        & Sajeeb Lohani (@sml555_)
=====================================================
[14:45:15] [THREAD] [echo file3] Added to Queue 
[14:45:15] [THREAD] [echo file2] Added to Queue 
Generated 2 commands in total
Repeat set to 1
file3                                                                                                                                               

file2                                                                                                                                               

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 269.33it/s]
root@kali-linux:/tmp/interlace_testing# 
#HOW IS IT PRINTING file2 and file3 when file2 and file3 are provided in -tL 
```
Also, when i do manually it works
```
root@kali-linux:/tmp/interlace_testing# ls
file1  file2  file3  filelist
root@kali-linux:/tmp/interlace_testing# filename="file1"
root@kali-linux:/tmp/interlace_testing# interlace -tL $filename -threads 8 -c "echo _target_"
=====================================================
Interlace v1.8.2        by Michael Skelton (@codingo_)
                        & Sajeeb Lohani (@sml555_)
=====================================================
[14:46:03] [THREAD] [echo data1] Added to Queue 
[14:46:03] [THREAD] [echo data2] Added to Queue 
Generated 2 commands in total
Repeat set to 1
data1                                                                                                                                               

data2                                                                                                                                               

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 399.57it/s]
root@kali-linux:/tmp/interlace_testing# filename="file2"
root@kali-linux:/tmp/interlace_testing# interlace -tL $filename -threads 8 -c "echo _target_"
=====================================================
Interlace v1.8.2        by Michael Skelton (@codingo_)
                        & Sajeeb Lohani (@sml555_)
=====================================================
[14:46:08] [THREAD] [echo data4] Added to Queue 
[14:46:08] [THREAD] [echo data3] Added to Queue 
Generated 2 commands in total
Repeat set to 1
data3                                                                                                                                               

data4                                                                                                                                               

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 316.79it/s]
root@kali-linux:/tmp/interlace_testing# filename="file3"
root@kali-linux:/tmp/interlace_testing# interlace -tL $filename -threads 8 -c "echo _target_"
=====================================================
Interlace v1.8.2        by Michael Skelton (@codingo_)
                        & Sajeeb Lohani (@sml555_)
=====================================================
[14:46:12] [THREAD] [echo data6] Added to Queue 
[14:46:12] [THREAD] [echo data5] Added to Queue 
Generated 2 commands in total
Repeat set to 1
data6                                                                                                                                               

data5                                                                                                                                               

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 385.10it/s]
root@kali-linux:/tmp/interlace_testing# 
```

**Comment by machinexa2** [comment]
Also, the error is not because of using xargs or tr. Instead this error occurs when using `while read var` 
```
root@kali-linux:/tmp/interlace_testing# ls | xargs | tr ' ' '\n' | xxd
00000000: 6669 6c65 310a 6669 6c65 320a 6669 6c65  file1.file2.file
00000010: 330a                                     3.
root@kali-linux:/tmp/interlace_testing# echo -ne "file1\nfile2\nfile3\n" | xxd
00000000: 6669 6c65 310a 6669 6c65 320a 6669 6c65  file1.file2.file
00000010: 330a                                     3.
root@kali-linux:/tmp/interlace_testing# 
```
See its same

**Comment by machinexa2** [comment]
When a single file is used then this occurs 
```
root@kali-linux:/tmp/interlace_testing# ls
file1  file2  file3
root@kali-linux:/tmp/interlace_testing# #HERE FILE1 EXIST
root@kali-linux:/tmp/interlace_testing# #HERE file1 EXIST
root@kali-linux:/tmp/interlace_testing# #NOW LETS USE IN WHILE READ
root@kali-linux:/tmp/interlace_testing# echo "file1" | while read filename
> do
> echo $filename #VERIFYING $filename isnt empty and $filename == "file1"
> sleep 3
> interlace -tL $filename -threads 8 -c "echo _target_"
> done
file1
=====================================================
Interlace v1.8.2        by Michael Skelton (@codingo_)
                        & Sajeeb Lohani (@sml555_)
=====================================================
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.8.2', 'console_scripts', 'interlace')())
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.8.2-py3.8.egg/Interlace/interlace.py", line 32, in main
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.8.2-py3.8.egg/Interlace/interlace.py", line 11, in build_queue
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.8.2-py3.8.egg/Interlace/lib/core/input.py", line 277, in process_commands
Exception: No target provided, or empty target list
root@kali-linux:/tmp/interlace_testing# 
```

**Comment by machinexa2** [comment]
I made a example program like interlace which works.
```
root@kali-linux:/tmp/interlace_testing# python3 test.py -tL hi
YES
['i am content of hi', 'i am content of hihi']
root@kali-linux:/tmp/interlace_testing# echo "hi" | while read url 
> do
> python3 test.py -tL $url
> done
YES
['i am content of hi', 'i am content of hihi']
root@kali-linux:/tmp/interlace_testing# 
```
test.py content == 
```
root@kali-linux:/tmp/interlace_testing# cat test.py 
from argparse import ArgumentParser
parser = ArgumentParser(description='hi')
parser.add_argument('-tL', '--target-list', help='list of target')
argv = parser.parse_args()
if argv.target_list:
    print("YES")
    data = [line.rstrip('\n') for line in open(argv.target_list)]
    print(data)
root@kali-linux:/tmp/interlace_testing# 
```
hi content == 
```
root@kali-linux:/tmp/interlace_testing# cat hi
i am content of hi
i am content of hihi
root@kali-linux:/tmp/interlace_testing# 
```

**Comment by machinexa2** [comment]
I found out error is in code sys.stdin.isatty() , so when we use isatty() , along with `while read`, its basically reading from stdin which causes this error. I created a pull request to fix this error.

**Comment by machinexa2** [comment]
fixed, closing it
