### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not _io.TextIOWrapper

### ISSUE THREAD

**Issue by jffin** [codingo/Interlace#117]
Hi, I'm experiencing a strange issue.

```Traceback (most recent call last):
  File "/usr/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.8.2', 'console_scripts', 'interlace')()
  File "/usr/lib/python3.8/site-packages/Interlace-1.8.2-py3.8.egg/Interlace/interlace.py", line 32, in main
  File "/usr/lib/python3.8/site-packages/Interlace-1.8.2-py3.8.egg/Interlace/interlace.py", line 11, in build_queue
  File "/usr/lib/python3.8/site-packages/Interlace-1.8.2-py3.8.egg/Interlace/lib/core/input.py", line 255, in process_commands
  File "/usr/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not _io.TextIOWrapper```

**Comment by xnand** [comment]
quick and dirty fix for end users:

```python
os.stat(str(path))
```

on line 19 in genericpath.py

**Comment by jffin** [comment]
Thanks a lot, this hack works :)

**Comment by prodigysml** [comment]
Not too sure if this is our error or another package, but closing since there is an awesome quickfix in the thread. Great job @xnand!
