### ISSUE TITLE
Does not work when the targets are not IP addresses after the recent update

### ISSUE THREAD

**Issue by fyoorer** [codingo/Interlace#123]
After the recent major update, interlace is not working for targets other than IP addresses.
Example targets file:
```
test
test2
```

`interlace -tL /tmp/targets.txt -c "echo _target_"`

Error:
```
=====================================================
Interlace v1.9.0        by Michael Skelton (@codingo_)
& Sajeeb Lohani (@sml555_)
=====================================================
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/strategy/ipv4.py", line 125, in str_to_int
return _struct.unpack('>I', _inet_pton(AF_INET, addr))[0]
OSError: illegal IP address string passed to inet_pton

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/ip/__init__.py", line 311, in __init__
self._value = self._module.str_to_int(addr, flags)
File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/strategy/ipv4.py", line 129, in str_to_int
raise AddrFormatError('%r is not a valid IPv4 address string!' % (addr,))
netaddr.core.AddrFormatError: 'test' is not a valid IPv4 address string!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/ip/__init__.py", line 791, in parse_ip_network
ip = IPAddress(val1, module.version, flags=INET_PTON)
File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/ip/__init__.py", line 313, in __init__
raise AddrFormatError('base address %r is not IPv%d'
netaddr.core.AddrFormatError: base address 'test' is not IPv4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/strategy/ipv4.py", line 265, in expand_partial_address
tokens = ['%d' % int(addr)]
ValueError: invalid literal for int() with base 10: 'test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/ip/__init__.py", line 927, in __init__
value, prefixlen = parse_ip_network(module, addr,
File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/ip/__init__.py", line 795, in parse_ip_network
expanded_addr = _ipv4.expand_partial_address(val1)
File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/strategy/ipv4.py", line 267, in expand_partial_address
raise error
netaddr.core.AddrFormatError: invalid partial IPv4 address: 'test'!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/bin/interlace", line 11, in <module>
load_entry_point('Interlace==1.9.0', 'console_scripts', 'interlace')()
File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.0-py3.8.egg/Interlace/interlace.py", line 36, in main
File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.0-py3.8.egg/Interlace/lib/threader.py", line 93, in __init__
File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.0-py3.8.egg/Interlace/interlace.py", line 11, in task_queue_generator_func
File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.0-py3.8.egg/Interlace/lib/core/input.py", line 249, in process_data_for_tasks_iterator
File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.0-py3.8.egg/Interlace/lib/core/input.py", line 210, in _process_targets
File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.0-py3.8.egg/Interlace/lib/core/input.py", line 207, in parse_and_group_target_specs
File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/ip/sets.py", line 121, in __init__
for cidr in cidr_merge(mergeable):
File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/ip/__init__.py", line 1555, in cidr_merge
cidr = IPNetwork(ip)
File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/ip/__init__.py", line 938, in __init__
raise AddrFormatError('invalid IPNetwork %s' % (addr,))
netaddr.core.AddrFormatError: invalid IPNetwork test
```

**Comment by whiteroses** [comment]
Thanks for the report. Non-IP-address targets that contain a period are working, but those that do not contain a period are not -- I've submitted [a PR](https://github.com/codingo/Interlace/pull/124) that fixes this.

**Comment by AdmiralGaust** [comment]
Please fix this.....I have built my templates around this. I use _target_ as the name of my target (example: yahoo)

**Comment by prodigysml** [comment]
Checked if this issue has been resolved:
```
interlace -tL /tmp/x -c "echo _target_"
=====================================================
Interlace v1.9.1	by Michael Skelton (@codingo_)
                  	& Sajeeb Lohani (@sml555_)
=====================================================
  0%|                                                                                                                                                                                 | 0/2 [00:00<?, ?it/s][23:54:46] [THREAD] [echo test2] Added to Queue
[23:54:46] [THREAD] [echo test] Added to Queue
test2

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 493.39it/s]Generated 2 commands in total
Repeat set to 1
test

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 296.20it/s]
```

```
cat /tmp/x
test
test2
```

Can confirm, issue is now patched.

**Comment by prodigysml** [comment]
Sorry about any trouble caused there @AdmiralGaust!
