### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by knowthetech** [codingo/Interlace#148]
updating: ['11046']
updating: ['97']
Traceback (most recent call last):
File "/usr/local/bin/interlace", line 11, in
load_entry_point('Interlace==1.9.5', 'console_scripts', 'interlace')()
File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.5-py3.8.egg/Interlace/interlace.py", line 36, in main
File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.5-py3.8.egg/Interlace/lib/threader.py", line 101, in init
File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.5-py3.8.egg/Interlace/interlace.py", line 11, in task_queue_generator_func
File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.5-py3.8.egg/Interlace/lib/core/input.py", line 258, in process_data_for_tasks_iterator
File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.5-py3.8.egg/Interlace/lib/core/input.py", line 218, in _process_targets
File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.5-py3.8.egg/Interlace/lib/core/input.py", line 195, in parse_and_group_target_specs
IndexError: string index out of range

**Comment by prodigysml** [comment]
Hey @knowthetech, can you please provide some reproduction steps? Would be useful for figuring out what happened.

**Comment by knowthetech** [comment]
Actually i was using jsfscan and using large subdomain list sometimes make me stuck here

**Comment by xYantix** [comment]
@knowthetech does this mean it's no longer an issue?

**Comment by knowthetech** [comment]
It's  an issue even now it happens when checking long subdomain list

**Comment by xYantix** [comment]
Hey @knowthetech, if this is still happening can you please provide some more information so that it can be reproduced? 
For example, what commands were you running?
How large was the file you were working with? 
If you use a smaller version of the same file with the same commands, does it still error? eg. Just use 1/4 of the file for testing.

**Comment by knowthetech** [comment]
That file consist of aprrox 100 subdomains but when i try to check manually it's  happening for some subdomains else working fine for others.

**Comment by knowthetech** [comment]
the command i am using is "./JSFScan.sh -l sites.txt -all -r"

**Comment by knowthetech** [comment]
interlace -tL live_jsfile_links.txt -threads 5 -c

file contains 245 urls
