### ISSUE TITLE
No package metadata was found for Interlace

### ISSUE THREAD

**Issue by Silentsoul04** [codingo/Interlace#156]
Facing this issue while installing 

sudo python3 setup.py install

```

/usr/local/lib/python3.7/dist-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/usr/local/lib/python3.7/dist-packages/setuptools/command/easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing manifest file 'Interlace.egg-info/SOURCES.txt'
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/Interlace
creating build/bdist.linux-x86_64/egg/Interlace/lib
creating build/bdist.linux-x86_64/egg/Interlace/lib/core
byte-compiling build/bdist.linux-x86_64/egg/Interlace/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/Interlace/interlace.py to interlace.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/Interlace/lib/threader.py to threader.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/Interlace/lib/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/Interlace/lib/core/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/Interlace/lib/core/input.py to input.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/Interlace/lib/core/output.py to output.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/Interlace/lib/core/__version__.py to __version__.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying Interlace.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Interlace.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Interlace.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Interlace.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Interlace.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Interlace.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Removing /usr/lib/python3.7/site-packages/Interlace-1.9.5-py3.7.egg
Copying Interlace-1.9.5-py3.7.egg to /usr/lib/python3.7/site-packages
```

interlace 

```
Command 
Traceback (most recent call last):
  File "/usr/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.5', 'console_scripts', 'interlace')())
  File "/usr/bin/interlace", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 951, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 542, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for Interlace
```

**Comment by vansh1** [comment]
same, do you got any solution please tell me
