### ISSUE TITLE
ModuleNotFoundError: No module named 'Interlace

### ISSUE THREAD

**Issue by vansh1** [codingo/Interlace#158]
Traceback (most recent call last):
  File "/usr/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.5', 'console_scripts', 'interlace')())
  File "/usr/bin/interlace", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'Interlace'

**Comment by Dazaiii1** [comment]
Hey try use a lower version of python3 , I switched to Python 3.6.9 and it worked fine

**Comment by amirnsahmad** [comment]
The bin is being generated in wrong folder in some cases.

Use this command: (probably you need to change the Python version in PATH):

```
cp /usr/lib/python3.8/site-packages/* /usr/local/lib/python3.8/dist-packages/
```

**Comment by amirnsahmad** [comment]
Sorry, the correct is

```cp -r /usr/lib/python3.8/site-packages/* /usr/local/lib/python3.8/dist-packages/```

**Comment by prodigysml** [comment]
Was this issue all fixed, or were people still seeing issues?

**Comment by rishikesh-j** [comment]
> Sorry, the correct is
> 
> `cp -r /usr/lib/python3.8/site-packages/* /usr/local/lib/python3.8/dist-packages/`

This worked for me.
