### ISSUE TITLE
Intr

### ISSUE THREAD

**Issue by shifty0g** [codingo/Interlace#163]
Not sure if it likes new version of python 

```
uname -a 
Linux kali 5.16.0-kali7-amd64 #1 SMP PREEMPT Debian 5.16.18-1kali1 (2022-04-01) x86_64 GNU/Linux

python3 --version       
Python 3.10.4
```

## Steps to replicate 

Literally git clone this repo

```
cd Interlace  
python3 setup.py install 
```

when i try to then load interlace it dies 

```
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.6', 'console_scripts', 'interlace')())
  File "/usr/local/bin/interlace", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/Interlace-1.9.6-py3.10.egg/Interlace/interlace.py", line 6, in <module>
  File "/usr/local/lib/python3.10/dist-packages/Interlace-1.9.6-py3.10.egg/Interlace/lib/core/output.py", line 4, in <module>
  File "/usr/local/lib/python3.10/dist-packages/colorclass-2.2.0-py3.10.egg/colorclass/__init__.py", line 11, in <module>
  File "/usr/local/lib/python3.10/dist-packages/colorclass-2.2.0-py3.10.egg/colorclass/codes.py", line 4, in <module>
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

any ideas what im doing wrong here.   i have reverted snapshot and tried on a fresh kali vm but no go. seems like interlace dont play ball with the latest python

**Comment by 0xtavian** [comment]
@prodigysml hey bud, i can confirm interlace isnt playing nicely with the latest python.  Taking the temp fix from
https://github.com/pry0cc/axiom/issues/555#issuecomment-1133745166 fixes the issue. Seem to be a bug in the latest python?

adding the following line `from collections.abc import Mapping` to 
```
/usr/lib/python3.10/collections/init.py
/usr/lib/python3.10/collections/__init__.py
```

**Comment by Jesse415** [comment]
> @prodigysml hey bud, i can confirm interlace isnt playing nicely with the latest python. Taking the temp fix from [pry0cc/axiom#555 (comment)](https://github.com/pry0cc/axiom/issues/555#issuecomment-1133745166) fixes the issue. Seem to be a bug in the latest python?
> 
> adding the following line `from collections.abc import Mapping` to
> 
> ```
> /usr/lib/python3.10/collections/init.py
> /usr/lib/python3.10/collections/__init__.py
> ```

How can I add this to AWS AMI so when I lunch axiom-fleet I don't have to ssh in individually can add these?

**Comment by prodigysml** [comment]
Thanks for the heads up @0xtavian ! Yeah, that seems like a weird issue with the latest python. I'll see if there is anything we can do to fix this up (maybe changing the data structure we use or something).

**Comment by prodigysml** [comment]
Ahhh! Its used by our colouring dependency
