### ISSUE TITLE
How can I run interlace as background process?

### ISSUE THREAD

**Issue by Crankle437** [codingo/Interlace#32]
Hi,

how can I run interlace over ssh as background process?
```
nohup interlace -tL ./targets.txt -threads 5 -c "nikto --host _target_:_port_ > ./_target_-_port_-nikto.txt" -p 80,443 &

Interlace v1.3.3        by Michael Skelton (@codingo_)
==============================================
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.3.3', 'console_scripts', 'interlace')()
  File "/usr/local/lib/python3.6/dist-packages/Interlace-1.3.3-py3.6.egg/Interlace/interlace.py", line 24, in main
  File "/usr/local/lib/python3.6/dist-packages/Interlace-1.3.3-py3.6.egg/Interlace/interlace.py", line 10, in build_queue
  File "/usr/local/lib/python3.6/dist-packages/Interlace-1.3.3-py3.6.egg/Interlace/lib/core/input.py", line 125, in process_commands
OSError: [Errno 9] Bad file descriptor
```

Thank you

**Comment by codingo** [comment]
@Crankle437 given the implementation this won't be possible like  this, but you would be able to accomplish the same thing by binding it to a `tmux` or `session` instance

**Comment by nadirio** [comment]
@codingo Does this mean it wouldn't work with cron as well? I have tried it with cron, but it did not seem to be working. Same error basically.
