### ISSUE TITLE
1.6.2 returns AttributeError: 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by br-sn** [codingo/Interlace#68]
Hi folks,

Just installed interlace 1.6.2 on a clean ubuntu VM and confirmed this is also happening on a Kali VM.

Running interlace with a list of targets or a single target gives me the following output:

`
Traceback (most recent call last):

  File "/usr/local/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.6.2', 'console_scripts', 'interlace')()
  File "/usr/local/lib/python3.6/dist-packages/Interlace-1.6.2-py3.6.egg/Interlace/interlace.py", line 25, in main
  File "/usr/local/lib/python3.6/dist-packages/Interlace-1.6.2-py3.6.egg/Interlace/interlace.py", line 11, in build_queue
  File "/usr/local/lib/python3.6/dist-packages/Interlace-1.6.2-py3.6.egg/Interlace/lib/core/input.py", line 243, in process_commands
  File "/usr/local/lib/python3.6/dist-packages/Interlace-1.6.2-py3.6.egg/Interlace/lib/core/input.py", line 171, in _replace_variable_with_commands

AttributeError: 'str' object has no attribute 'name'
`

Tested with python 3.6.8 on Ubuntu 18.10.

**Comment by prodigysml** [comment]
Issue is on this line: https://github.com/codingo/Interlace/blob/a1557e7dfd297897255c147c3f2f6bab1320663d/Interlace/lib/core/input.py#L171

`command` variable is a string (`str` object).

**Comment by codingo** [comment]
@br-sn we should have a fix shortly. Will update here once it lands.

**Comment by prodigysml** [comment]
I think the issue occurs here:
https://github.com/codingo/Interlace/blob/a1557e7dfd297897255c147c3f2f6bab1320663d/Interlace/lib/core/input.py#L238-L241

The first condition is a string, whereas the second is a list of Task objects.

**Comment by codingo** [comment]
Fixed in #69
