### ISSUE TITLE
Exception in interlace first time run

### ISSUE THREAD

**Issue by Rzqu** [codingo/Interlace#84]
I seem to be hitting an issue when utilising interlace to run multiple nikto scans, this is the first time i have installed interlace and instructions were followed.

Below is the error im getting, i noticed the failed to detect a valid IP address error but it seems a strange response, the .txt file contains domain names.

```
[root@localhost results]# interlace -tL ./example.txt -threads 4 -c "nikto --host _target_ > ./_target_-nikto.txt" -v
=====================================================
Interlace v1.7.2	by Michael Skelton (@codingo_)
                  	& Sajeeb Lohani (@sml555_)
=====================================================
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.7.2', 'console_scripts', 'interlace')()
  File "/usr/local/lib/python3.7/site-packages/Interlace-1.7.2-py3.7.egg/Interlace/interlace.py", line 26, in main
  File "/usr/local/lib/python3.7/site-packages/Interlace-1.7.2-py3.7.egg/Interlace/interlace.py", line 11, in build_queue
  File "/usr/local/lib/python3.7/site-packages/Interlace-1.7.2-py3.7.egg/Interlace/lib/core/input.py", line 258, in process_commands
  File "/usr/local/lib/python3.7/site-packages/Interlace-1.7.2-py3.7.egg/Interlace/lib/core/input.py", line 158, in _pre_process_hosts
  File "/usr/local/lib/python3.7/site-packages/Interlace-1.7.2-py3.7.egg/Interlace/lib/core/input.py", line 53, in _get_ips_from_range
  File "/usr/local/lib/python3.7/site-packages/netaddr-0.7.19-py3.7.egg/netaddr/ip/__init__.py", line 1357, in __init__
    self._start = IPAddress(start, flags=flags)
  File "/usr/local/lib/python3.7/site-packages/netaddr-0.7.19-py3.7.egg/netaddr/ip/__init__.py", line 306, in __init__
    'address from %r' % addr)
netaddr.core.AddrFormatError: failed to detect a valid IP address from '\x1b[92mmobile'
```

**Comment by xYantix** [comment]
@Rzqu Can you try with a fresh list of different domains and confirm if this happens again? The way I read that error suggests it has an issue with an entry in the target List file.

**Comment by Rzqu** [comment]
> @Rzqu Can you try with a fresh list of different domains and confirm if this happens again? The way I read that error suggests it has an issue with an entry in the target List file.

My bad, i messed up my previous command that generated my list, i didnt check the list before i opened the issue - i should probably sleep lol.

Thanks

**Comment by xYantix** [comment]
Great news! Go get some sleep :)
